version: "3.9"


services:
  redis:
    image: "redis:alpine"
    # expose:
    #   - 6379
    ports:
      - "6379:6379"
    # network_mode: host
  web:
    # restart: "always"
    build: .
    depends_on:
      - redis
    ports:
      - "5000:5000"
    # network_mode: host

  web-worker:
    # restart: "always"
    build: .
    command: celery -A app.celery worker
    # network_mode: host
